# Generated by Django 2.1.7 on 2019-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190502_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', max_length=200, null=True, upload_to='avatar/%Y/%m/%d', verbose_name='用户头像'),
        ),
    ]
