# Generated by Django 2.1.7 on 2019-04-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DmhyAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='标题')),
                ('name_url', models.TextField(verbose_name='链接')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('zimuzu', models.TextField(max_length=250, verbose_name='字幕组')),
                ('zimuzu_url', models.URLField(verbose_name='字幕组链接')),
                ('fenlei', models.CharField(max_length=250, verbose_name='分类')),
                ('daxiao', models.CharField(max_length=250, verbose_name='大小')),
                ('faburen', models.CharField(max_length=250, verbose_name='发布人')),
                ('faburen_url', models.TextField(verbose_name='发布人链接')),
                ('xiazai_url', models.TextField(verbose_name='磁链')),
            ],
            options={
                'verbose_name': '动漫花园数据',
                'verbose_name_plural': '动漫花园数据',
            },
        ),
    ]
