# Generated by Django 2.1.7 on 2019-03-25 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bduss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bduss', models.TextField(verbose_name='BDUSS')),
                ('username', models.CharField(editable=False, max_length=250, verbose_name='百度用户名')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'BDUSS设置',
                'verbose_name_plural': 'BDUSS设置',
            },
        ),
        migrations.CreateModel(
            name='SignTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='签到时间')),
            ],
            options={
                'verbose_name': '签到时间',
                'verbose_name_plural': '签到时间',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TiebaMeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_name', models.CharField(editable=False, max_length=250, verbose_name='名称')),
                ('forum_id', models.CharField(editable=False, max_length=50, verbose_name='贴吧ID')),
                ('is_sign', models.BooleanField(default=False, editable=False, help_text='判断该贴吧签到没有', verbose_name='是否签到')),
                ('user_exp', models.IntegerField(editable=False, verbose_name='经验')),
                ('user_level', models.IntegerField(editable=False, verbose_name='等级')),
                ('note', models.CharField(default='', editable=False, max_length=50, verbose_name='备注')),
                ('username', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tieba.Bduss', verbose_name='百度用户名')),
            ],
            options={
                'verbose_name': '贴吧列表',
                'verbose_name_plural': '贴吧列表',
                'ordering': ['user_level'],
            },
        ),
        migrations.AddField(
            model_name='signtime',
            name='name',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tieba.TiebaMeList', verbose_name='贴吧名字'),
        ),
    ]
