# Generated by Django 2.1.7 on 2019-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bduss',
            name='bduss_id',
            field=models.CharField(default='', editable=False, max_length=500, verbose_name='贴吧用户中心网址'),
        ),
    ]
