# Generated by Django 2.1.7 on 2019-03-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0002_bduss_bduss_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bduss',
            name='bduss_id',
        ),
    ]
