# Generated by Django 2.1.7 on 2019-04-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0003_remove_bduss_bduss_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baidu_zhidao', models.BooleanField(default=False, editable=False, help_text='签到知道请打勾', verbose_name='是否签到百度知道')),
                ('baidu_wenku', models.BooleanField(default=False, editable=False, help_text='签到文库请打勾', verbose_name='是否签到百度文库')),
                ('username', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tieba.Bduss', verbose_name='百度用户')),
            ],
        ),
    ]
