# Generated by Django 2.1.7 on 2019-04-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0004_signconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signconfig',
            name='username',
        ),
    ]
