# Generated by Django 2.1.7 on 2019-04-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0005_remove_signconfig_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signconfig',
            options={'verbose_name': '签到设置', 'verbose_name_plural': '签到设置'},
        ),
    ]
