# Generated by Django 2.1.7 on 2019-05-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0011_bduss_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bduss',
            name='usernames',
            field=models.CharField(default='', max_length=250, verbose_name='百度用户名(验证用)'),
        ),
    ]
