# Generated by Django 2.1.7 on 2019-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0013_auto_20190522_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bduss',
            name='username_false',
            field=models.CharField(default='0', editable=False, max_length=250, verbose_name='BDUSS失效时间记录（单位：天）'),
        ),
    ]
