# Generated by Django 2.1.7 on 2019-05-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0014_bduss_username_false'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bduss_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_false', models.DateTimeField(editable=False, verbose_name='BDUSS失效时间记录')),
                ('email_send', models.DateTimeField(editable=False, verbose_name='发送BDUSS失效邮件的时间记录')),
            ],
        ),
        migrations.RemoveField(
            model_name='bduss',
            name='username_false',
        ),
        migrations.AddField(
            model_name='bduss_time',
            name='username',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tieba.Bduss', verbose_name='百度用户名'),
        ),
    ]
