# Generated by Django 2.1.7 on 2019-05-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0015_auto_20190531_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bduss_time',
            options={'verbose_name': '失效BDUSS时间记录', 'verbose_name_plural': '失效BDUSS时间记录'},
        ),
        migrations.RemoveField(
            model_name='bduss_time',
            name='email_send',
        ),
    ]
