# Generated by Django 2.1.7 on 2019-05-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0016_auto_20190531_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bduss_time',
            name='username_false',
            field=models.DateTimeField(auto_now=True, verbose_name='BDUSS失效时间记录'),
        ),
    ]
