# Generated by Django 2.1.7 on 2019-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0017_auto_20190531_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='bduss_time',
            name='email_send',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否已发送当日邮件'),
        ),
    ]
