# Generated by Django 2.1.7 on 2019-05-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('index', models.IntegerField(default=999, verbose_name='分类排序(从小到大)')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(blank=True, verbose_name='时间')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
            ],
            options={
                'verbose_name': '网站发展流程设置',
                'verbose_name_plural': '网站发展流程设置',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('callback_url', models.URLField(verbose_name='URL地址')),
                ('description', models.CharField(max_length=200, verbose_name='链接描述')),
                ('img', models.ImageField(blank=True, default='avatar/default.jpg', max_length=200, null=True, upload_to='gateway/%Y/%m', verbose_name='图标')),
                ('date_publish', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gateway.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '导航页设置',
                'verbose_name_plural': '导航页设置',
            },
        ),
    ]
