# Generated by Django 2.1.7 on 2019-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='img',
            field=models.ImageField(blank=True, default='avatar/default.jpg', max_length=200, null=True, upload_to='gateway/%Y/%m/%d', verbose_name='图标'),
        ),
    ]
