# Generated by Django 2.1.7 on 2019-05-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20190502_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
